# default
spring:
  profiles:
    active: local #default
    group:
      local:
        - secret
        - file # local + secret + file 실행
        - security
      prod:
        - secret
        - file
        - security
      test:
        - secret
        - file
        - security
---
spring:
  config:
    activate:
      on-profile: local # local + secret 실행
---
spring:
  config:
    activate:
      on-profile: prod # prod + secret
---
spring:
  config:
    activate:
      on-profile: test
